### ISSUE TITLE
Tumblr大部分视频无法播放

### ISSUE THREAD

**Issue by mailgggg** [wangchunming/2017hosts#1]
但是也有一些视频是可以播放的，有办法解决吗？老D的hosts也有这个问题

**Comment by wangchunming** [comment]
无法解决，即使是用了缓存的话速度也上不去，不过我会在一个星期之后的更新里面尽力尝试解决的，谢谢你的提醒

**Comment by mailgggg** [comment]
好的，多谢回复

**Comment by wangchunming** [comment]
感谢您的支持。
手机版hosts于今日更新，除了play音乐和游戏无法使用还有网络定位无法使用外其他谷歌服务已经恢复到最好状态，twitter和facebook还有ins亲测可用。
