### ISSUE TITLE
望君安好

### ISSUE THREAD

**Issue by hohhoo** [wangchunming/2017hosts#1]

**Comment by thisisandy** [comment]
望君安好

**Comment by helenterry** [comment]
以后还是不要留个人信息吧，保护好自己比较重要。希望一切没事。

**Comment by wh9007** [comment]
还是开辟新的途径吧.  暗号

**Comment by Ibuki-Suika** [comment]
暗号比较安全，但是不好传播（毕竟有人到现在想上google都没找到方法。。。）

**Comment by wh9007** [comment]
慢慢的建立圈子嘛,我只是建议而已;

其它的都很不太安全.很容易被查水表.


事业一定争取,对你从未放弃


________________________________
发件人: Ibuki-Suika <notifications@github.com>
发送时间: 2017年7月13日 0:01
收件人: wangchunming/2017hosts
抄送: 陶醉; Comment
主题: Re: [wangchunming/2017hosts] 望君安好 (#1)


暗号比较安全，但是不好传播（毕竟有人到现在想上google都没找到方法。。。）

―

**Comment by BBDXF** [comment]
世道艰难，愿君安好~

**Comment by caofengzi** [comment]
阿彌陀佛

**Comment by fytz007** [comment]
望君安好
