### ISSUE TITLE
你好,有关联通校园网问题.

### ISSUE THREAD

**Issue by oenstep** [wangchunming/2017hosts#101]
有一段时间没用,现在替换了最新版本hosts-pc后发现能打开youtube却无法播放youtube视频
vedioplayback一直pending处于failed状态,无法获取视频.
用的是锐捷客户端,之前是没什么问题的.

**Comment by wangchunming** [comment]
这个情况我知道的，现在电信快起来了移动也行就是联通慢。

现在没法解决，因为找不到更好的代理ip了。

**Comment by oenstep** [comment]
知道了,看不了也没办法,起码能用google,wiki,还是非常感谢的.
