### ISSUE TITLE
希望增加这几个

### ISSUE THREAD

**Issue by LisPerfect** [wangchunming/2017hosts#13]
#Origin Start
origin.com 23.213.148.86 
eaassets-a.akamaihd.net 61.213.149.16 
23.211.98.54 data1.origin.com 
23.211.98.54 data2.origin.com 
23.211.98.54 data3.origin.com 
23.211.98.54 data4.origin.com 
23.211.98.54 api1.origin.com 
23.211.98.54 api2.origin.com 
104.118.139.126 api3.origin.com 
184.27.231.87 api4.origin.com 
#Origin End

#Steam Start
104.80.124.80 store.steampowered.com
68.232.45.131 store.edgecast.steamstatic.com
125.64.134.83 cdn.steamstatic.com.8686c.com
65.158.122.146 images.akamai.steamusercontent.com
65.158.122.145 steamcdn-a.akamaihd.net
65.158.122.160 steamcommunity-a.akamaihd.net
172.230.215.214 steamcommunity.com
65.158.122.187 cloud-3.steamusercontent.com
#Steam End

**Comment by wangchunming** [comment]
恩，好的，这个会在下次更新时添加进hosts。
