### ISSUE TITLE
gmail打开失败

### ISSUE THREAD

**Issue by redapple0204** [wangchunming/2017hosts#14]
提示
>错误

>您所请求的网址（URL）无法获取

**Comment by LisPerfect** [comment]
你发下错误代码，我四川电信是没问题的

**Comment by redapple0204** [comment]
@LisPerfect 
![2017-03-04 11-53-14](https://cloud.githubusercontent.com/assets/16254644/23575920/415da740-00d1-11e7-9a08-3fbfa1886a79.png)

**Comment by LisPerfect** [comment]
你尝试一下
ipconfig /flushdns

**Comment by redapple0204** [comment]
我是linux.....

**Comment by wangchunming** [comment]
前面加个s就行了，以https打开

**Comment by redapple0204** [comment]
@wangchunming I know
但是以前用那个r什么的hosts就不会啊==
手动加https很麻烦，特别是手机端很难聚焦

**Comment by wangchunming** [comment]
这只是一个别名，你可以通过mail.google.com的方式进去啊。
