### ISSUE TITLE
大佬，几个网站不成敬意 咳咳，要是能教教我该有多好

### ISSUE THREAD

**Issue by caibuyaodajijimengmei** [wangchunming/2017hosts#16]
正经点的（才怪）     
                                  opskins.com
                                  cloudflare.com
                                  ecchi.iwara.tv
                                   www.twitch.tv
                                   chan.sankakucomplex.com
                                   www.nicovideo.jp
                                    www.dlsite.com

**Comment by wangchunming** [comment]
好的，不久之后的更新我就会添加这些域名。（cloudflare.com并未被墙）

**Comment by caibuyaodajijimengmei** [comment]
可是，可是我为什么上不去cloudflare.com，还望大佬能解析下这个网址，挺多网站靠这个域名的，应该有不小的 助益的

**Comment by omaidb** [comment]
大佬，测试的youtube你的速度最给力

**Comment by Outzzz** [comment]
手机的host貌似出问题了。网页谷歌能用 play不能用

**Comment by omaidb** [comment]
我也发现了
caibuyaodajijimengmei <notifications@github.com>于2017年3月10日 周五14:48写道：

**Comment by wangchunming** [comment]
我已经添加了 twitchtv和cloudflare了，其他网站无法添加所以没有添加。

**Comment by omaidb** [comment]
更新给力点哦
王春明 <notifications@github.com>于2017年3月11日 周六14:26写道：
