### ISSUE TITLE
duckduckgo无法上去

### ISSUE THREAD

**Issue by rayfine** [wangchunming/2017hosts#21]
电信网络，无法连接duckduckgo.com。

$ ping www.duckduckgo.com
PING www.duckduckgo.com (46.51.216.186) 56(84) bytes of data.
^C
--- www.duckduckgo.com ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2032ms

**Comment by wangchunming** [comment]
嗯，我会在下次更新的时候另找官方IP，更了之后我通知你哦。

**Comment by wangchunming** [comment]
如果还有其他无法使用的服务，也请及时反馈。

**Comment by wangchunming** [comment]
duckduckgo没有可用官方IP了，我下次更会想别的办法的。

**Comment by wangchunming** [comment]
已经修复，感谢支持。
