### ISSUE TITLE
google没法用了！

### ISSUE THREAD

**Issue by redapple0204** [wangchunming/2017hosts#23]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

IP 地址：219.76.4.11
时间：2017-03-16T13:50:04Z
网址：https://ipv4.google.com/sorry/index

**Comment by wangchunming** [comment]
因为用的人多才会这样，能输入验证码吗？

**Comment by redapple0204** [comment]
不能

**Comment by redapple0204** [comment]
@wangchunming 可以了，thx

**Comment by ChauncyZhang** [comment]
这个我也经常出现
