### ISSUE TITLE
都散了吧，看下commit提交记录，就知道是炒作了，七月才建的新项目

### ISSUE THREAD

**Issue by calabash519** [wangchunming/2017hosts#24]

**Comment by wangchunming** [comment]
该项目删除过两次。

**Comment by wangchunming** [comment]
![](http://ww2.sinaimg.cn/large/006HJ39wgy1fhlcrvk92lj30ve0flq3q.jpg)
![](http://ww1.sinaimg.cn/large/006HJ39wgy1fhlcrvm9b1j30yk0fy0tx.jpg)

**Comment by arthurchan35** [comment]
我5月份开始用的，请不要随意污蔑别人的工作。。。

**Comment by paperbag** [comment]
@calabash519 我查了一下 能够找到这个 repo 之前别人的 fork https://github.com/codemanagercenter/2017hosts

@wangchunming 话说现在这个是你本人吗 我看到 readme 有这么一句话 是什么意思？
> WALL具备刺探TLS的能力（可以知道你访问的URL详细地址并且可以拿到交换的证书也可以检查提交的表单）

**Comment by dou4cc** [comment]
@paperbag 在你不删掉CNNIC之流的CA、使用国产软件的情况下。否则GFW只能拿到证书
