### ISSUE TITLE
facebook messenger无法使用。

### ISSUE THREAD

**Issue by EFCHolla** [wangchunming/2017hosts#26]
Facebook messenger无法使用，显示在不断尝试连接网络，手机端和PC端都是相同情况。
请问能有可能解决吗？谢谢！

**Comment by wangchunming** [comment]
好，下次更新会解决的，你有什么问题请继续回复。

**Comment by wangchunming** [comment]
网页版刚才测试了一下没问题，客户端有，下次更新会解决的。

**Comment by EFCHolla** [comment]
好的，非常感谢。
请问你是怎么获取这些IP的，网上有没有什么教程？
