### ISSUE TITLE
问一下，您的项目和那个racaljk的项目有啥区别啊

### ISSUE THREAD

**Issue by zhuweijia** [wangchunming/2017hosts#27]
我是从那个racaljk的hosts项目里，看您发布的twitter ip地址知道您的，您发布的地址是不是和他们类似？
还有看说明里，说youtube可以看视频？？一般不是hosts无法做到播放视频吗？还是说您的可以？
或者是手机端可以用youtube客户端看？？
纯小白，请原谅

**Comment by wangchunming** [comment]
额，唯一的区别就是我的地址是IPV4他的是IPV6（不适合一般用户），他的包含的网站和我hosts包含的网站也是有多少区别的，hosts可以看视频，电脑和手机都行，反应速度其实可以的，无论是客户端或者网页都行。

**Comment by wangchunming** [comment]
我针对不同的设备应用了不同的ip和域名方案，而它只是一份。

**Comment by zhuweijia** [comment]
好吧，你的包含的网站比他多还是？还是你们的侧重点不同？，明天试试你的hosts试试

**Comment by wangchunming** [comment]
嗯，多是肯定的，
