### ISSUE TITLE
你好，请问能否把https://play.google.com/music  hosts加上去啊。谢谢！

### ISSUE THREAD

**Issue by wh9007** [wangchunming/2017hosts#29]
你好，请问能否把https://play.google.com/music  hosts加上去啊。谢谢！

**Comment by wangchunming** [comment]
play音乐是可以正常打开的，但是因为香港不支持使用play音乐所以无法使用在线音乐播放功能。

**Comment by wangchunming** [comment]
目前没有解决办法。
目前亚洲仅有日本，印度等国家支持使用play音乐在线播放功能。

**Comment by wh9007** [comment]
请问你的HOSTS 文件多久更新一次啊.


事业一定争取,对你从未放弃


________________________________
发件人: 王春明 <notifications@github.com>
发送时间: 2017年3月28日 18:41
收件人: wangchunming/2017hosts
抄送: 陶醉; Author
主题: Re: [wangchunming/2017hosts] 你好，请问能否把https://play.google.com/music hosts加上去啊。谢谢！ (#29)


Closed #29<https://github.com/wangchunming/2017hosts/issues/29>.

―

**Comment by wangchunming** [comment]
其实提交的反馈多了以后，根据情况就会更新。
一般情况下是3-30天更新一次。
我最近比较忙，没什么大问题就不会频繁更新了。
