### ISSUE TITLE
其实我在想这个名义和时间究竟是怎么定的

### ISSUE THREAD

**Issue by wolgy** [wangchunming/2017hosts#29]
看了一圈关于扰乱公共秩序的条目，并没有适用条目。
而且就算有，好像拘留十天最多也就是十五天吧。
最后，祝好。

**Comment by Ninzero** [comment]
@wolgy 大概是……“传授犯罪方法罪”？

**Comment by babizhu** [comment]
拘留不可能1个月啊，不是钓鱼贴吧
