### ISSUE TITLE
IOS替换了hosts 无法联网

### ISSUE THREAD

**Issue by zxloveyyy** [wangchunming/2017hosts#3]
IOS 和安卓都用不起  PC可以用 youtube速度很快

**Comment by wangchunming** [comment]
谢谢你的提醒，我将会在以后的时间内解决这个问题，您是属于哪个省份的？还有，如果有什么其他意见或者建议也欢迎及时跟进回复哦

**Comment by wangchunming** [comment]
最近将会对苹果手机出一个专版，因为苹果手机找ip不像安卓那么严。

**Comment by wangchunming** [comment]
第一版苹果的测试有问题，可以保证访问google并同步chrome但是其他软件都无法正常使用，正在慢慢修复。。。

**Comment by wangchunming** [comment]
手机版hosts已经修复了ip了，你可以下载试试看，感谢你的支持。

**Comment by wangchunming** [comment]
首先谢谢你的支持。
我已经按照你的要求把手机版完全修复好了。

**Comment by wangchunming** [comment]
感谢您的支持。
手机版hosts于今日更新，除了play音乐和游戏无法使用还有网络定位无法使用外其他谷歌服务已经恢复到最好状态，twitter和facebook还有ins亲测可用。

**Comment by zxloveyyy** [comment]
我的IOS还是不行呢.不知道什么原因

**Comment by wangchunming** [comment]
你可以在电脑上先用第三方工具把你手机那份hosts拿到桌面上，然后下载这里的hosts用复制hosts内条目的方式放进你从手机里拿出来的那个文件（用notepad编辑），然后保存，把那个文件放回去。。。你可以试试的

**Comment by zxloveyyy** [comment]
搞了半天可以用了,谢谢了
