### ISSUE TITLE
大家不要再用这个hosts了

### ISSUE THREAD

**Issue by toprapid** [wangchunming/2017hosts#30]
这个hosts文件里的ip地址，指向的是中国电信全球公司，而不是google公司，明显是被电信劫持了的。虽然通过电信公司的转向可以访问，但你们输入的密码，以及任何敏感的内容，都可以被他监测到。如果没有什么敏感内容，用用倒也无妨，就是要注意一些网站不要乱看，小心被查水表。

**Comment by Naville** [comment]
是的因为中国电信可以解密Google的https

/Sarcasm
