### ISSUE TITLE
你好,希望能把这些站点加在hosts文件内

### ISSUE THREAD

**Issue by dimonwei** [wangchunming/2017hosts#31]
这是一个图片素材的网站,在国内不知道为什么有时候打不开,或者十分缓慢,请帮忙看一下呢?
https://unsplash.com/
这是安卓APK的下载站点基本无法访问
http://apkpure.com/
十分感谢

**Comment by wangchunming** [comment]
哦，好的，还有就是apkpure的话我之前在手机上的hosts里都已经加上了的。
你前面说的那个网址的话我有时间我检查一下能不能加，能加我就加上。
