### ISSUE TITLE
你好请帮忙维护下www.instagram.com

### ISSUE THREAD

**Issue by silencebbb** [wangchunming/2017hosts#33]
首先感谢 无偿无私的服务 ，我看好多网站地址引流到香港VPS？是你自费的么？
随着用的人原来越多，会不会越来越卡，项目什么时候会终止，毕竟是要收费的。
www.instagram.com  是图片无法正常显示
最后 
再一次感谢。

**Comment by wangchunming** [comment]
是电脑还是手机上的？你所处的网络运营商是？

**Comment by silencebbb** [comment]
是电脑上 目前显示连接重置  用的电信但是网上查是 联通 本机IP: 114.112.193.83北京市西城区 联通

**Comment by wangchunming** [comment]
已修复，感谢你的支持。
