### ISSUE TITLE
www.instagram.com测试图片已经修复另外问几个问题谢谢

### ISSUE THREAD

**Issue by silencebbb** [wangchunming/2017hosts#34]
还是老问题啦，因为看到有的地址通过香港中转，请问流量费是否你个人承担？
另外是否这个需要对外宣传，当然知道的人越多肯定会越来越卡。
谢谢
感谢

**Comment by silencebbb** [comment]
另外问下有没有想过弄成DNS的模式可以挂在路由器里。方便家里所有设备上网。建立个DNS服务器。

**Comment by silencebbb** [comment]
#hosts-pc last update 2017-3-15

#LocalHost start
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
127.0.1.1 hostname
#LocalHost end

另外这里的版本号忘记更新啦

**Comment by wangchunming** [comment]
有什么建议或者反馈的话望请及时跟进，谢谢。

**Comment by silencebbb** [comment]
好的谢谢！辛苦了！
