### ISSUE TITLE
电信网络无法同步

### ISSUE THREAD

**Issue by JsonLocker** [wangchunming/2017hosts#34]
感谢作者，github上这么多hosts里面你这个最好用，或者最适合这边的网络。。只是最近google浏览器经常无法正常同步，另外youtube相对前阵子会稍显lag。希望有空可以帮修复下，再次感谢无私付出！

**Comment by wangchunming** [comment]
电脑上啊还是手机上啊，电脑的话我看看，手机的hosts的话现在还没调整好。。。。

**Comment by JsonLocker** [comment]
电脑上的，福建电信网络。系统是win10， 17020588版本

**Comment by tiger0313** [comment]
今天使用PotPlayer播放youtube视频怎么弄都播放不出来，昨天还好好的，不知道什么原因

**Comment by tiger0313** [comment]
有什么方法能解决openload视频的流畅播放，谢谢

**Comment by JsonLocker** [comment]
可以尝试更换youtube播放，最近是这样子的。有些视频可以播放有些不行，能播放的视频缓冲时间不大稳定。比如这个地址https://www.youtube.com/watch?v=1SROJXK9G68&index=1&list=PLVmaHFXy6tlcBGKBEIKIRyiKKNpIhLaiu，播单第一个关于蓝灯的可以播放，但是缓冲时间要半分钟左右，下面的视频就很快。 希望对你会有所帮助。

**Comment by wangchunming** [comment]
的确看不了，过段时间我看下。

在 2017年7月30日 下午6:02，Json_M <notifications@github.com>写道：
