### ISSUE TITLE
确实能看Youtube但是其他网站会比较慢

### ISSUE THREAD

**Issue by yixiaoqingyuz** [wangchunming/2017hosts#36]
确实能看YouTube了，不过看720p就比较卡了，我是电信网络，用蓝灯看720p非常流畅，不过已经非常厉害了，感谢您的共享。
此外我发现我这里有个不太好的地方，就是访问其他外网的速度明显比我用的另外一个不能看Youtube的hosts文件慢，包括谷歌，推特等，都感觉明显慢了很多，我不知道什么原因，我把地址贴出来，您看看：https://github.com/racaljk/hosts

**Comment by silencebbb** [comment]
YOUTUBE是不快不过免费的我也不说啥。

**Comment by wangchunming** [comment]
youtube慢的话，我会换ip的，等以后更新吧。

**Comment by wangchunming** [comment]
解决了。

**Comment by wangchunming** [comment]
抱歉了几位，经过四个小时的调试，今天更新的hosts解决了这些问题，请用最新的吧，然后手机ip失效我也更新了新的ip。
