### ISSUE TITLE
能能添加dailymotion的hosts?

### ISSUE THREAD

**Issue by cw2012** [wangchunming/2017hosts#39]
这个网站也被屏蔽了。要是能通过修改hosts文件访问就好了。

**Comment by wangchunming** [comment]
我测试了一下，并不是这个网站出问题了，而是它页面的某些元素的域名被墙了，不过这很好解决，几天之内的更新我就把这个问题解决掉。

**Comment by wangchunming** [comment]
已经解决了，请你下载最新的hosts检查一下，谢谢。
