### ISSUE TITLE
请教一些小问题

### ISSUE THREAD

**Issue by theratlesnake** [wangchunming/2017hosts#4]
首先祝作者新年快乐！
提示：所有在hosts内的属于代理类的ip均支持翻墙之后代理http，具体用途大家懂~
请问下，这个是什么意思哦？本人技术菜鸟，谢谢

**Comment by wangchunming** [comment]
额，首先谢谢你。
在国外使用像hosts内的219.7*.*.*这类ip的话是可以直接代理http的，也就是说你比方说美国vps回国网络太慢，你其实就可以在vps上添加一些转发规则或者借助

**Comment by wangchunming** [comment]
额，首先谢谢你。
在国外使用像hosts内的219.7*.*.*这类ip的话是可以直接代理http的，也就是说你比方说美国vps回国网络太慢，你其实就可以在vps上添加一些转发规则或者借助

**Comment by wangchunming** [comment]
额，首先谢谢你。
在国外使用像hosts内的219.7*.*.*这类ip的话是可以直接代理http的，也就是说你比方说美国vps回国网络太慢，你其实就可以在vps上添加一些转发规则或者借助一些修改dns的手法，将速度慢的域名指向到这里，这样速度就上去了。
还有就是在海外，自己的网站担心海外cdn流量费太贵等问题的话，也是可以将海外区域的网站dns记录指向这里的，香港和国内解析到原站，海外解析到这里就好，可以实现完美的加速体验

**Comment by theratlesnake** [comment]
噢，可惜我不在国外啊，是不是就用不上这种功能了？

**Comment by theratlesnake** [comment]
@jzp820927 把大神也at 上，求解

**Comment by jzp820927** [comment]
GAE 懂点，这个没研究过，找其他大神吧

**Comment by zhaoliyingmmd** [comment]
@theratlesnake 其实就是cdn的问题，具体可以百度cdn

**Comment by theratlesnake** [comment]
@zhaoliyingmmd  感觉太复杂了，在vps上添加什么转发规则，这些还是给玩技术的人来吧

**Comment by wangchunming** [comment]
感谢您的支持。
手机版hosts于今日更新，除了play音乐和游戏无法使用还有网络定位无法使用外其他谷歌服务已经恢复到最好状态，twitter和facebook还有ins亲测可用。
