### ISSUE TITLE
google.com打不开

### ISSUE THREAD

**Issue by kouzhaokui** [wangchunming/2017hosts#41]
山东联通，Google.com打不开但是能ping通YouTube正常，请问有解决办法不QAQ

———————————————————————————————————————————————
修改dns为114dns后正常了，都能打开了。

**Comment by wangchunming** [comment]
大哥，俺也是山东人啊，老家东营滴！
我这边测试没你说的问题，当然，第一版hosts出现了这个问题。。。。。

**Comment by kouzhaokui** [comment]
啊啊啊，改了个dns服务器，突然就打开了，哈哈哈，俺是临沂滴
