### ISSUE TITLE
Dailymotion无法播放视频

### ISSUE THREAD

**Issue by EFCHolla** [wangchunming/2017hosts#41]
能够打开主页，但是无法播放视频。

**Comment by wangchunming** [comment]
暂无解决方案，抱歉。

**Comment by Furybb** [comment]
@wangchunming 看twitch会有很严重的卡顿，有好的办法吗？

**Comment by wangchunming** [comment]
dailymotion视频播放问题完美解决，下一步尝试解决twitch问题

**Comment by EFCHolla** [comment]
@wangchunming 请问你是怎么保证https链接的，https everywhere?
我添加了static1.dmcdn.net和static2.dmcdn.net后有时候能够播放视频了，但是要等很长时间，有时候还是不行。

**Comment by wangchunming** [comment]
@EFCHolla chrome://net-internals > hsts
