### ISSUE TITLE
现在youtube视频基本上打不开了，两个版本都一样很难打开

### ISSUE THREAD

**Issue by tiger0313** [wangchunming/2017hosts#43]

**Comment by yizhidouzai** [comment]
是的，能点进去，但是不能播放

**Comment by wh9007** [comment]
同样的问题.感觉速度慢!

**Comment by wangchunming** [comment]
麻烦亲们反馈问题的时候带上你使用的网络和省份好吗？

**Comment by wangchunming** [comment]
我检查了一下，第一版是我发错了。。。。

**Comment by Zobeta** [comment]
今天的第二版连打开youtube网页都相当勉强了

**Comment by wangchunming** [comment]
![](http://ww3.sinaimg.cn/large/0060lm7Tgy1fi4c16x7tyj311x0lc7tl.jpg)

嗯，我这里移动看着没啥问题。（第二版）
第一版是电信的问题。。。
我想想办法吧，youtube是hosts项目创建以来的老大哪那。

**Comment by wh9007** [comment]
加油啊.我的幸福,全在你身上啊.

同时.自己好好的!

事业一定争取,对你从未放弃


________________________________
发件人: 王春明 <notifications@github.com>
发送时间: 2017年8月1日 17:06
收件人: wangchunming/2017hosts
抄送: 陶醉; Comment
主题: Re: [wangchunming/2017hosts] 现在youtube视频基本上打不开了，两个版本都一样很难打开 (#43)


[https://camo.githubusercontent.com/4e1f91ce262182d54c472eca0c9119f9baac7c76/687474703a2f2f7777332e73696e61696d672e636e2f6c617267652f303036306c6d3754677931666934633136783774796a33313178306c6337746c2e6a7067]<https://camo.githubusercontent.com/4e1f91ce262182d54c472eca0c9119f9baac7c76/687474703a2f2f7777332e73696e61696d672e636e2f6c617267652f303036306c6d3754677931666934633136783774796a33313178306c6337746c2e6a7067>

嗯，我这里移动看着没啥问题。（第二版）
第一版是电信的问题。。。
我想想办法吧，youtube是hosts项目创建以来的老大哪那。

―
