### ISSUE TITLE
请求添加http://www.clipconverter.cc/的host

### ISSUE THREAD

**Issue by 1990chs** [wangchunming/2017hosts#45]
用暴力候的clipconverter.cc来下载youtube视频，但是网站经常打不开，求相关的host！

**Comment by LisPerfect** [comment]
用youtube-dl更好用
https://github.com/rg3/youtube-dl

**Comment by EFCHolla** [comment]
推荐用IDM

**Comment by 1990chs** [comment]
@LisPerfect 主要是用油猴脚本集成在浏览器中。
