### ISSUE TITLE
新版hosts谷歌打不开，https握手失败（湖南电信）

### ISSUE THREAD

**Issue by dengxionghui** [wangchunming/2017hosts#46]
183那个谷歌代 理ip 可以ping通，但是网页打不卡，火狐提示安全连接建立失败，chrome提示服务器意外终止连接，wireshark抓取183那个服务器的数据包发现syn同步建立连接后出现fin ack关闭连接的包，换用其它host正常，应该不是电脑的问题，联通和移动也一样的情况，移动偶尔可以打开

![1](https://user-images.githubusercontent.com/23251507/28817201-1366358a-76da-11e7-99b3-bf1569e5741e.PNG)
![2](https://user-images.githubusercontent.com/23251507/28817217-1f1f5aaa-76da-11e7-9359-f710f5aae123.PNG)
![3](https://user-images.githubusercontent.com/23251507/28817229-249d7b7e-76da-11e7-89ea-1c043b059ed1.PNG)
![4](https://user-images.githubusercontent.com/23251507/28817231-27e0b620-76da-11e7-9788-f1b7691b6ea7.PNG)
![5](https://user-images.githubusercontent.com/23251507/28817245-2d02a604-76da-11e7-89b1-dfaf7afd7aa8.PNG)

**Comment by peteyan** [comment]
貌似不稳定
