### ISSUE TITLE
应用hosts文件后自github下载文件时存在异常

### ISSUE THREAD

**Issue by batkiz** [wangchunming/2017hosts#48]
具体情况为：
应用 hosts文件后如果 从github下载时下载器（ ADM 、迅雷 ）会一直显示  _正在获取信息_ ，不能下载。
已知hosts-mobile 与 hosts-pc 均存在此问题，望排查。

**Comment by LisPerfect** [comment]
我也是，当我从github-cloud.s3.amazonaws.com上下载东西时就会挂

**Comment by wangchunming** [comment]
嗯，请期待之后的更新。
4.29日更新修复了手机line和dropbox打不开问题，现在还剩一个telegram和gmail打不开的问题需要解决。

**Comment by wangchunming** [comment]
我非常感谢像你一样热心详细反馈问题的支持者，谢谢。

**Comment by wangchunming** [comment]
我更新hosts的最终目的就是不用让大多数用户挂梯子就可以享受到外网的服务。

**Comment by wangchunming** [comment]
已解决！谢谢反馈
