### ISSUE TITLE
打不开百度首页和NY Times

### ISSUE THREAD

**Issue by helenterry** [wangchunming/2017hosts#49]
1、大概不到一个月前，在使用wifi时无法打开https://www.baidu.com ，偶尔能打开http://www.baidu.com ，最近两者大部分时间都打不开，不过使用手机4G热点就能打开。不知道跟替换了hosts有没有直接关联啊？

2、用edge和IE打开https://www.nytimes.com/ 显示：
无法安全地连接到此页面
这可能是因为该站点使用过期的或不安全的 TLS 安全设置。如果这种情况持续发生，请与网站的所有者联系。
TLS 安全设置未设置为默认设置，这也可能导致此错误。

用Chrome打开则显示：
无法访问此网站
网址为 https://www.nytimes.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_SSL_UNRECOGNIZED_NAME_ALERT

不知道是New York Times被墙了的原因还是我自己电脑设置的原因？

**Comment by wangchunming** [comment]
前者跟hosts没有任何关系。
后者我检查了一下是nytimeswww的那个换ip了，手机版的话是m.nytimes则没事。
下一次更新会调整的。

**Comment by wangchunming** [comment]
手机版ip也被封了，下一次更新会解决。

**Comment by helenterry** [comment]
了解，感谢回复~

**Comment by wangchunming** [comment]
恩，下期更新计划是这样的。
添加voachinese和大纪元全套网址（毕竟有好多人想要），然后再把mytimes修复掉。
然后再看看stream速度太慢如何解决。

对了，如果你想要添加什么网址的话你可以继续回复，支持https就行。

**Comment by wangchunming** [comment]
已经解决了，

**Comment by helenterry** [comment]
非常感谢！！
