### ISSUE TITLE
作者好，我请教一下关于路由器的问题

### ISSUE THREAD

**Issue by meikeeit** [wangchunming/2017hosts#5]
如果在主路由上加入了hosts解析文件，是不是所有的设备都可以使用，类似直接在DNS上更改hosts，另外谢谢你做的这些，给很多人提供便利

**Comment by wangchunming** [comment]
某些基于openwrt的路由器是可以这么做的，但是这还牵扯到一个问题，手机如果需要google play的话就不能用电脑的hosts（因为app不支持https sni），这个只能说你自己看情况针对的修改一下了，我相信上github的都不是懒人，你试试吧，祝你好运，谢谢。

**Comment by meikeeit** [comment]
前天晚上把路由刷了Pandora box，用的PC版的hosts，用了两天没什么大问题，就是g+里的链接不能用浏览器打开，忘记是 404还是什么了

**Comment by wangchunming** [comment]
g+里的短链接都是需要https打开的，不然就会报错。

**Comment by wangchunming** [comment]
首先感谢你的支持。
如果路由器上配置pc版hosts无法让移动设备使用服务的话你可以让移动设备单独替换hosts，我已经按照反馈问题的网友把手机版hosts修复好了，谷歌应用的侧栏头像和背景都是可以显示的了，速度也快了不少。

**Comment by wangchunming** [comment]
感谢您的支持。
手机版hosts于今日更新，除了play音乐和游戏无法使用还有网络定位无法使用外其他谷歌服务已经恢复到最好状态，twitter和facebook还有ins亲测可用。
路由器上直接放这个也可以的哦。
