### ISSUE TITLE
最近正准备筹备免费SS项目，需要你们的主意。

### ISSUE THREAD

**Issue by wangchunming** [wangchunming/2017hosts#53]
如题，因为更新hosts是在是令人体验无法满意，虽然我已经花了非常多的心思在上面，但是还是没法做到在任何网络下都能顺畅使用的这种样子，所以我决定提供些免费SS给无论是支持hosts项目的老朋友还是新朋友去用，因为现在依然在使用hosts的人大多肯定都是没有什么经济条件去单独购买SS的人，或者是太好的线路个人买不起（天价），所以就没在用的人。
自从这个hosts项目，从2015年7月我接手以来，版本至少出了几千次了，在用的人我之前做过一个问卷，也有不到一万人了，首先谢谢各位在这一年多来的鼎力支持。
只要得到大多数人支持，我肯定会办的，并且打算一年之内办起来。

不过现在有一些事情需要大家帮我出出主意，或者讨论一下，或者有些事情需要告诉我：
1.因为众所周知的原因，在电信下面随便一条线路的话，翻墙速度那的确是很慢的，但是同时也是有很多好线路的，你们有没有什么国外服务商的好线路但是价格太贵一个人承受不起的那种？
2.一个人一般使用SS能最大占用到多少带宽？（限制流量的话有可能会让一部分人还是用不爽）如果免费SS项目以后能办起来的话我尽量会让大家用得爽（但是因为我钱不是很多，也不能说是人人4K的程度，人人1080p那绝对可以）。
3.为防止滥用，.服务禁止BT和25端口发邮件（465可以用），不知道大家有没有意见？
4.为了避免频繁被封，更换服务器的麻烦，那么请问各位，你们认为连接信息用什么传播方式比较好？（或者是不要给外部圈子人用？）
5.国内中转因为费用太高，我肯定没有办法为各位提供（如果提供的话那么也就需要各位捐助支持了，那就不是免费的SS了），不知道有其他人是否愿意为用的人提供国内中转服务？

**Comment by tiger0313** [comment]
支持一下，虽然我什么都不懂，720p就满足了

**Comment by chaizemin** [comment]
其实能保证720p就可以，当然了，清晰度越高越好，国内网络环境各有不同，无法确保所有平台都能保证，只要尽力就好，在此谢过

**Comment by GaoSheng1** [comment]
推荐用xx-net。1080P一点压力没有

**Comment by darrenliuwei** [comment]
能冒昧的问一下吗？SS怎么使用啊？我还从来没用过。

**Comment by kniht11** [comment]
ss筹备的怎么样了

**Comment by redapple0204** [comment]
其实已经有许多这样的博主做了
例如doub.io以及https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

**Comment by Buruconglin** [comment]
现在免费ss其实很多，再弄一个其实作用不能算大，翻墙的工具应是多样化的，建议可以尝试一些新工具如pipesocks等等。
