### ISSUE TITLE
关于重复的问题

### ISSUE THREAD

**Issue by Ninzero** [wangchunming/2017hosts#55]
你好，我很喜欢这个项目，所以我希望能尽一些力。正好看到有人提了去重的issue，但是再去重的过程中发现以下的内容，一个url对应了两个IP地址，应该如何处理？
`1.bp.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`2.bp.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`3.bp.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`4.bp.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`googleblog.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`chrome.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`android-developers.blogspot.com 	 183.91.33.46 	 219.76.4.11`
`external.fhkg3-2.fna.fbcdn.net 	 219.76.57.145 	 219.76.57.209`
`en.gravatar.com 	 192.0.80.239 	 192.0.80.240`

**Comment by wangjake** [comment]
hello 我是你的项目的受益者，非常感谢你的项目可以让我很愉快看youtube和用google查阅资料。
但是我在用tumblr时候，几乎所有视频无法加载。能否帮看下 是什么问题？
感激不尽！

**Comment by Ninzero** [comment]
tumblr的网页版不能播放视频，请仔细看ReadMe开头的提示

**Comment by Ninzero** [comment]
？？？为什么关闭？

**Comment by Ninzero** [comment]
为什么关闭这个issue？？？ @wangchunming
