### ISSUE TITLE
Youtube视频手机上无法播放

### ISSUE THREAD

**Issue by helenterry** [wangchunming/2017hosts#57]
电脑上用edge可以正常播放，WP10手机用edge无法播放，一直是视频缓冲状态，评论神马的倒是都能正常显示。试了联通4G和wifi都播放不了。

**Comment by Powww** [comment]
我可以呀

**Comment by wangchunming** [comment]
请问你是使用的哪个运营商的网络啊？所在省份是哪个？如果方便的话请提供公网IP用来查路由走向。

**Comment by helenterry** [comment]
我是上海联通的网络，公网ip是啥？

**Comment by helenterry** [comment]
啊我刚刚又试了下4g，发现可以看了，回头我再试下wifi
