### ISSUE TITLE
请问该项目以何许可证发行？

### ISSUE THREAD

**Issue by PeratX** [wangchunming/2017hosts#57]
本人准备将该项目添加到 https://github.com/iTXTech/Daedalus 的 hosts 列表中。

**Comment by wangchunming** [comment]
没有许可，任何人都可以拿去使用。

2017年8月23日 10:22，"PeratX" <notifications@github.com>写道：

**Comment by PeratX** [comment]
https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh 这个可能比较有参考价值。
