### ISSUE TITLE
steam商店，和origin平台的记录，有问题，还不如裸连，我是上海电信

### ISSUE THREAD

**Issue by Powww** [wangchunming/2017hosts#58]
能改进吗

**Comment by wangchunming** [comment]
有什么问题？加载不出来还是加载慢？回答后我会详细排查一下。

**Comment by Powww** [comment]
第一个是steam的问题，添加购物车后，结账页面打不开，裸连可以支付
截图是这样的：
[http://blog.pppow.top/wp-content/uploads/2017/05/QQ截图20170525210534.png](url)
Invalid SSL Certificate

The SSL certificate for https://store.steampowered.com/checkout/?purchasetype=self is invalid and the page will not be loaded.
第二个是
origin平台登录后的页面根本加载不出来吗，不如裸连
有问题
#Origin Start
23.213.148.86 origin.com
23.213.148.86 www.origin.com
61.213.149.16 eaassets-a.akamaihd.net
23.211.98.54 data1.origin.com
23.211.98.54 data2.origin.com
23.211.98.54 data3.origin.com
23.211.98.54 data4.origin.com
23.211.98.54 api1.origin.com
23.211.98.54 api2.origin.com
104.118.139.126 api3.origin.com
184.27.231.87 api4.origin.com
#Origin End

**Comment by wangchunming** [comment]
恩，好的，谢谢你的反馈，我会尽快在端午节假期结束之前解决你的问题。

**Comment by wangchunming** [comment]
已换CDN。
