### ISSUE TITLE
github的不太稳定，有时候连不上

### ISSUE THREAD

**Issue by marjax** [wangchunming/2017hosts#59]
试了下裸连连得是192.30.255.112这个IP，和hosts里设置的是192.30.255.113这个。但是两个都不稳定，常常无法连接。用dns工具查了github.com也只有这两个地址可以用。生活在国内好累啊，上个github都要和GFW斗智斗勇。

**Comment by wangchunming** [comment]
但是如果用代理的话那么就不支持git工具使用了，暂时还没有其他办法解决。
