### ISSUE TITLE
Facebook登录不上了，可以帮忙更新一下吗？

### ISSUE THREAD

**Issue by darrenliuwei** [wangchunming/2017hosts#59]
你们能登录上Facebook吗？我的登录不上了。

**Comment by wangchunming** [comment]
过几天一起更。


other-proxy-soft那里新上架蓝灯安卓破解版，可以去试试，亲测能用，电信下速度出奇的快。

**Comment by darrenliuwei** [comment]
破解版？是可以突破每个月500M免费高速流量的限制吗？

**Comment by darrenliuwei** [comment]
我刚刚下载下来试用了一下，速度好慢啊！没有蓝灯官方给的快额

**Comment by darrenliuwei** [comment]
额(⊙o⊙)…现在速度变快了一些了，看视频网页等一点都不卡了，挺好用的，谢谢分享

**Comment by huidaoweilai2016** [comment]
Facebook 218.254.1.15 可以代理
