### ISSUE TITLE
twitter的ip貌似不可用

### ISSUE THREAD

**Issue by tonydeng** [wangchunming/2017hosts#6]
@wangchunming

**Comment by wangchunming** [comment]
额，电脑版还是手机版呢？手机版的话我在昨晚已经更新过一次，电脑版的话还要等些时间更新。
有问题或者意见请继续回复，谢谢。

**Comment by tonydeng** [comment]
电脑版

**Comment by pgz123** [comment]
+1,谢谢作者

**Comment by wangchunming** [comment]
感谢您的支持。
手机版hosts于今日更新，除了play音乐和游戏无法使用还有网络定位无法使用外其他谷歌服务已经恢复到最好状态，twitter和facebook还有ins亲测可用。

**Comment by tonydeng** [comment]
THX
