### ISSUE TITLE
请问可以增加对niconico的支持吗

### ISSUE THREAD

**Issue by yuanshengdv** [wangchunming/2017hosts#60]
用了这个hosts大半年的，更新的很频繁，也越来越稳定了，真的很感谢，我想请问一下能不能增加对niconico的支持，感谢作者！

**Comment by wangchunming** [comment]
嗯，首先非常谢谢你的支持。
下次更新我会尽力的。
今天刚刚解决了前段时间网友们集中反馈的问题。

**Comment by wangchunming** [comment]
niconico不支持https，暂时没办法。

**Comment by yuanshengdv** [comment]
谢谢，那我挂vpn看吧，主要是觉得挂vpn麻烦
