### ISSUE TITLE
检查了你的host

### ISSUE THREAD

**Issue by anglesgirl** [wangchunming/2017hosts#61]
发现你好多地方都是用的 中国香港 pccw.com提供的SNI，这不是一个好的行为，非常容易导致SNI服务商关闭服务，建议尽量使用官方原版可用IP，实在不得已才用SNI
特别是FACEBOOK这个喜欢封号的网站，使用官方IP是更加迫切的需要，免得莫名其妙被封号还找不到原因，就怪fb

**Comment by wangchunming** [comment]
这个已经有计划在做了，IP非常难找，为了保证体验暂时就只能用SNI了。
以后也是两个版本，SNI和官方IP。
还有啊，大陆运营商现在已经有根据返回证书杀IP的能力了，这也是一开始我为什么就用SNI的原因，墙去模拟连接IP看证书看不到啊，还有一点是保证速度。

**Comment by wangchunming** [comment]
嗯，拒绝服务的话要关（就是拒绝连接这种的，不是被墙），也是对大陆和海外全都关的。
最初其实这段ip也是当CDN用的。
电信出国慢这个是众多维护hosts的令他们烦人的地方。

**Comment by dou4cc** [comment]
gfw按证书封的ip过会儿会解封的，所以可像goproxy那样一直换ip连来达到高速
