### ISSUE TITLE
山东电信YouTube速度很差

### ISSUE THREAD

**Issue by MingqiHuang** [wangchunming/2017hosts#61]
如图，两个月前YouTube山东电信就开始掉速（最初速度40000kbps左右，后逐渐下降至不足200kbps），开始只是晚上速度很差（一个月前白天还是可以看720p的），现在全天几乎所有时段都不能取得很好的体验（不足200kbps），144p都卡，相反，说明上所述可能不适用的联通速度能达到5000kbps左右，是电信速度的若干倍。
望解决。
附图：
![pic](https://i.loli.net/2017/09/02/59aa680180000.png)

**Comment by wangchunming** [comment]
我这边莱芜移动也一样是五千左右，好点的时候能上一万
![](https://raw.githubusercontent.com/wangchunming/images-me/master/%E6%8D%95%E8%8E%B7.PNG)
好。知道了。

**Comment by MingqiHuang** [comment]
坐标：东营。
两个月前速度能到4w左右真是爽啊。现在暂时先用别的替代方案吧。
感谢您所做的努力。

**Comment by wangchunming** [comment]
我去。。。。。我老家东营广饶颜徐乡的。。。。。好

**Comment by MingqiHuang** [comment]
好巧。。。也是广饶人。。。县城的。。。

**Comment by wangchunming** [comment]
@MingqiHuang  沃特么老家离县城不远，就是开发区北边高赵刘村那里。

**Comment by wangchunming** [comment]
县城大部分地方google地图那里我都上传了街景了，例如佳乐超市广饶一中等等。。。。

**Comment by wangchunming** [comment]
已经更新hosts了，你再试试吧。
