### ISSUE TITLE
建议分块

### ISSUE THREAD

**Issue by wolfan** [wangchunming/2017hosts#62]
整体太大了私以为可以将Hosts切分成数个模块，建立一份基础模块包含常用的几家网站。
至于youtube之类可以独立一份文档。
大纪元、新唐人什么的，也可以让人按需添加也不错吖。

**Comment by Outzzz** [comment]
网搜《九评host》有真相？

在 2017年5月28日 下午6:07，wolfan <notifications@github.com>写道：

**Comment by wangchunming** [comment]
嗯，你的建议很好，近段时间会考虑的，等等吧。
