### ISSUE TITLE
请求添加https://forum.xda-developers.com

### ISSUE THREAD

**Issue by shangshiyjn** [wangchunming/2017hosts#63]
请问作者可以添加对https://forum.xda-developers.com的支持吗？XDA论坛里面有很多关于手机方面的好帖子，不知道为什么最近被墙了。。。多谢！

**Comment by wangchunming** [comment]
知道了，下次更新会处理这个问题。

**Comment by Ninzero** [comment]
[https://mailguru.s3.amazonaws.com/images/spark/qr.v2/935cf1c585724824a8e35714de5e0627.png]

谢谢！




Spark by Readdle<https://sparkmailapp.com>

**Comment by shangshiyjn** [comment]
@wangchunming 好的，谢谢😄

**Comment by wangchunming** [comment]
解决了。
