### ISSUE TITLE
教育网打不开突然Google了，，，很迷

### ISSUE THREAD

**Issue by kouzhaokui** [wangchunming/2017hosts#63]

**Comment by wangchunming** [comment]
这件事我知道的，我现在找不到能用的ip了，暂时没法换，你先用其他替代手段来访问吧，不好意思咯。

2017年9月8日 10:50，"kouzhaokui" <notifications@github.com>写道：

**Comment by kouzhaokui** [comment]
嗯，好吧

**Comment by wangchunming** [comment]
已经更新，谢谢支持。
