### ISSUE TITLE
希望能够修改wikipedia的地址

### ISSUE THREAD

**Issue by Ninzero** [wangchunming/2017hosts#64]
你好，在维基百科上可以找到维基媒体基金会公布的[地址](https://zh.wikipedia.org/wiki/User:LNDDYL/The_hosts_file_for_Wikimedia_projects)，使用目前的hosts文件访问wikipedia会导致只能看而无法进行编辑（维基百科会认为你正在使用代理），谢谢。

**Comment by wangchunming** [comment]
好的，知道了，下一次更新时处理这个问题。

**Comment by wangchunming** [comment]
解决了。
