### ISSUE TITLE
youtube打不开了

### ISSUE THREAD

**Issue by yizhidouzai** [wangchunming/2017hosts#64]

**Comment by wangchunming** [comment]
这件事我知道的，我现在找不到能用的ip了，暂时没法换，你先用其他替代手段来访问吧，不好意思咯。


2017年9月8日 11:32，"yizhidouzai" <notifications@github.com>写道：

**Comment by jinyumarine** [comment]
谷歌全挂了，望更新，谢谢

**Comment by wangchunming** [comment]
已更新，谢谢支持。
