### ISSUE TITLE
希望添加对time网站的支持

### ISSUE THREAD

**Issue by helenterry** [wangchunming/2017hosts#65]
网址是time.com 谢谢！

**Comment by wangchunming** [comment]
你好。
你所提供的网址经过测试，因为其并不是被dns污染而是被连接重置，并且该网站还不支持https的缘故，所以

**Comment by wangchunming** [comment]
所以无法

**Comment by wangchunming** [comment]
所以无法添加该网站。

**Comment by helenterry** [comment]
了解啦！谢谢~
话说我最近电脑没法正常登录github，用wifi和上海联通4g都要么打不开要么打开排版是混乱的，不过wp手机用edge可以正常登录。不知道是啥情况？
