### ISSUE TITLE
sublime text3 package install 下载插件失败

### ISSUE THREAD

**Issue by Hzhihua** [wangchunming/2017hosts#66]
在Ubuntu 16.04 Kylin版本中，安装sublime text3 之后，如果不把  /etc/hosts  里的  codeload.github.com  这一行注释掉则无法下载插件，windows7 无问题
\# 219.76.4.14 codeload.github.com

**Comment by wangchunming** [comment]
嗯，知道了。
现在官方ip在好多地方都是没法正常连接的，因此所以才用的代理。
我会想想办法的。
