### ISSUE TITLE
测试可用，不知道这个项目能坚持多久。毕竟用的人很多对VPS流量用的比较大。

### ISSUE THREAD

**Issue by silencebbb** [wangchunming/2017hosts#67]
而且大家都是伸手党。

**Comment by wangchunming** [comment]
你不用担心这个问题，流量没限制，问题在带宽上。

2017年9月11日 08:27，"silencebbb" <notifications@github.com>写道：

**Comment by wangchunming** [comment]
你不用担心这个问题，流量没限制，问题在带宽上。

2017年9月11日 08:27，"silencebbb" <notifications@github.com>写道：

而且大家都是伸手党。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wangchunming/2017hosts/issues/67>, or mute the thread

**Comment by wangchunming** [comment]
下一步还可能上digitalocean的。。。。

2017年9月11日 08:41，"王春明" <chunmingshq@gmail.com>写道：

**Comment by wangchunming** [comment]
Twitter和Facebook不可用的问题的话，Facebook我有办法，但是Twitter的话首先没法自建代理，其次就是ip被封干净了。

2017年9月11日 08:43，"王春明" <chunmingshq@gmail.com>写道：

**Comment by silencebbb** [comment]
好的 ，像你这样无私的人估计地球找不到了。。。问题又来了比如说卖流量和各种软件的人可能会拿你的这个IP当跳转，占用你带宽，攻击你服务器，举报你，因为你让他们利益损失。欸 干点事情真难啊。辛苦了！

**Comment by wangchunming** [comment]
没事，以后的时候我会做限制的，上digitalocean时候，从今往后我就会限制能代理的网址了，这个你放心就是，尽管用，不能用了就告诉我。

2017年9月11日 08:48，"silencebbb" <notifications@github.com>写道：

**Comment by silencebbb** [comment]
好的 十分感谢 ！另外怎么给你发邮件？可否把邮箱地址给我？谢谢。

**Comment by darrenliuwei** [comment]
@silencebbb 你直接点开他的GitHub主页，在左边就可以看到他的邮箱和他的个人网站。

**Comment by Ecareyu** [comment]
@wangchunming 小白想问下你是怎么做这种代理的，我曾经尝试过用nginx来代理，后来用了一段时间后就不行了，不知道能不能提示下呢？还有希望作者注意隐藏下自己的身份，以防万一，望安好！

**Comment by wangchunming** [comment]
8核16G的机器+apache(80端口)+nginx(8080和443端口)啊，机器性能好的话其实你遇到的问题根本不是事。

2017年9月11日 13:33，"Ecareyu" <notifications@github.com>写道：

**Comment by wangchunming** [comment]
443端口如果要做放扫的话就单独给ip在nginx里弄个vurtualhost，或者是用一些第三方软件直接拒绝ip方式连接到443端口。

2017年9月11日 13:36，"王春明" <chunmingshq@gmail.com>写道：

**Comment by Ecareyu** [comment]
意思就是说，其实你这边也是用nginx来实现的，我起初只是代理了youtube，尝试下压力，开始还流畅，后来好想被youtube本身给屏蔽了，因为其实就我一个人在用，不存在压力过大的情况吧，双核4G，香港独立vps

**Comment by wangchunming** [comment]
linux机器开了tcp
fastopen的，其次就是线路上要尽量选择不会被qos的线路，还有虚拟内存一定得设置，4G内存以上1G-4G就够用了，不设置的话运行内存的缓冲内存就能把物理内存吃干净，然后各种崩各种炸。
你这种情况其实并不是被youtube屏蔽了，要么服务商或者墙给随机性丢包了。
还有其实也是要选择允许建公开代理的服务商的。

2017年9月11日 13:53，"Ecareyu" <notifications@github.com>写道：

**Comment by wangchunming** [comment]
日志记录我都是关的，要么几千个ip连过来肯定日志得爆炸。

2017年9月11日 13:58，"王春明" <chunmingshq@gmail.com>写道：

**Comment by wangchunming** [comment]
有条件的话推荐直接在香港包独立家宽做这些事。

2017年9月11日 13:59，"王春明" <chunmingshq@gmail.com>写道：

**Comment by Ecareyu** [comment]
显然，没有这个条件，谢谢指点了，还是那句话，注意隐藏身份，还有谢谢的付出！
