### ISSUE TITLE
希望更改Onedrive地址

### ISSUE THREAD

**Issue by zhangyz1997** [wangchunming/2017hosts#67]
Onedrive其实有香港的CDN,在大陆访问的速度还是比较理想的
204.79.197.217 onedrive.live.com
用官方的地址我觉得会好一些

**Comment by wangchunming** [comment]
嗯，我知道了。
但是这个地址在全国70%以上的地方443端口都不通。

**Comment by wangchunming** [comment]
所以这就是用代理的原因。
