### ISSUE TITLE
github用电脑打开排版有问题

### ISSUE THREAD

**Issue by helenterry** [wangchunming/2017hosts#68]
最近电脑没法正常登录github，用wifi和上海联通4g都要么打不开要么打开排版是混乱的，不过wp手机用edge可以正常打开(mobile和desktop版都显示正常)。不知道是啥情况？

**Comment by wangchunming** [comment]
好的，我知道了，我会想办法的，如果你有什么后续问题可以继续回复，可以解决但没有解决问题的issues我不会关闭。

**Comment by wangchunming** [comment]
这个暂时没办法，抱歉。
