### ISSUE TITLE
抱歉，打搅下，今天貌似全部HOST失效

### ISSUE THREAD

**Issue by JohnWu17** [wangchunming/2017hosts#69]
9.19日下午2点左右，貌似HOST 全部失效，我更换了几个HOST，都无法链接，这个情况还是第一次出现，用的是深圳电信，不知道是个例还是全国性的。

**Comment by hnxals** [comment]
南京联通 +1

**Comment by wangchunming** [comment]
知道了，最近马上更。

**Comment by JohnWu17** [comment]
感谢感谢， 辛苦了

**Comment by JohnWu17** [comment]
感谢， 已经可以访问，不过YOUTUBE视频加载很慢，再次感谢。

**Comment by wangchunming** [comment]
@JohnWu17  你重下一遍，我修完了。

**Comment by JohnWu17** [comment]
@wangchunming 真的是非常感谢，非常感谢。 可以了

**Comment by JackieGG** [comment]
由衷感谢

**Comment by RickonChen** [comment]
@wangchunming 确实又恢复正常了！修复神速啊

**Comment by JohnWu17** [comment]
@wangchunming  不好意思， YOUTUBE 视频很多时候仍然加载不出来，能否麻烦在看下，谢谢

**Comment by lunaticliang** [comment]
要开19大了，上不去也是正常的

**Comment by lunaticliang** [comment]
@wangchunming 要开19大了，上不去也是正常的

**Comment by wpyok500** [comment]
目前，我这边照样不行。

**Comment by lunaticliang** [comment]
要开19大了，肯定封的厉害，要求就别那么高了

**Comment by smalldickman** [comment]
可以谷歌，但是一旦点击YouTube字样的链接，就马上挂掉，连Google也不行了，需要重新复制host，

**Comment by silencebbb** [comment]
今天好像恢复了 。感谢

**Comment by silencebbb** [comment]
facebook 还不行

**Comment by Lintion** [comment]
估计是youtube上最近有重磅炸弹，所以youtube和之前的twitter一样了，基本秒封

**Comment by weridname** [comment]
那现在的facebook可以上吗

**Comment by wangchunming** [comment]
大部分地区都不行。

2017年9月20日 09:55，"weridname" <notifications@github.com>写道：

**Comment by ckj1991** [comment]
江苏南通，重新更新hosts后还是全部失效，只有谷歌地图还可以用

**Comment by wangchunming** [comment]
恩，我想大麻烦来了。

2017年9月20日 13:19，"ckj1991" <notifications@github.com>写道：

**Comment by ckj1991** [comment]
什么大麻烦呀？是不是大陆要天黑了？？

**Comment by weridname** [comment]
赶紧黑了吧！~~我要上youtube看我的playboy!~~~~

**Comment by darrenliuwei** [comment]
好像只剩下Google搜索可以用了，其他都不能用了。
