### ISSUE TITLE
yt的播放问题。。。

### ISSUE THREAD

**Issue by samtone** [wangchunming/2017hosts#69]
现在看yt就像是摸奖一样。。打开10个视频有一个能看到 剩下都是出错。。。wangchunming还有办法解决一下吗。。。

**Comment by wangchunming** [comment]
这个问题我也是很头疼，暂时想不到更多办法，如果有什么办法的话我会把这个问题第一时间解决。

**Comment by wangchunming** [comment]
手机上可以靠单纯替换ip解决（没错，我已经发更新了），但是电脑上有点难办，正在解决。

**Comment by samtone** [comment]
wangchunming 非常感谢 辛苦了。。

**Comment by wangchunming** [comment]
暂时先上别的ip顶着，这个问题以后想办法。
