### ISSUE TITLE
能加个网站吗？

### ISSUE THREAD

**Issue by batkiz** [wangchunming/2017hosts#7]
ctext.org   63.141.239.58
这网站时能登时不能的，希望加上，若是已经有了，还请见谅。

**Comment by wangchunming** [comment]
okay，将在下一次更新时添加哦。
对了，目前情况是电脑hosts已经非常完善了，手机hosts还差需要解决网络定位和谷歌云盘视频预览问题就完美了。
如有什么意见或者建议欢迎继续跟进咯。

**Comment by batkiz** [comment]
谢谢
另，前两天我看了看hosts，发现你的格式有些乱啊=。=

**Comment by wangchunming** [comment]
恩，格式确实很乱。
如果你还有其他意见或者建议也请尽情拍砖。

**Comment by wangchunming** [comment]
感谢您的支持。
手机版hosts于今日更新，除了play音乐和游戏无法使用还有网络定位无法使用外其他谷歌服务已经恢复到最好状态，twitter和facebook还有ins亲测可用。
