### ISSUE TITLE
twitter这些天，访问有问题

### ISSUE THREAD

**Issue by kusion** [wangchunming/2017hosts#70]
twitter这些天，访问有问题。。。。。。
GFW好可恶心啊，让人上个网就这么折腾！

**Comment by wangchunming** [comment]
我看了一下，不是hosts的问题，恩，真有可能是墙变高按SNI杀连接了。

**Comment by wangchunming** [comment]
手机hosts更了，真正让你成为国内用户。

**Comment by wangchunming** [comment]
twitter访问有问题不是hosts的事情，现在全国都这样，无论什么ip指向twitter都是无法使用的。
