### ISSUE TITLE
youtube今天不能用了

### ISSUE THREAD

**Issue by yizhidouzai** [wangchunming/2017hosts#73]

**Comment by Lintion** [comment]
好像是qiang技术升级了，换IP后秒封。估计是针对域名做处理的，之前的twitter好像就是这么干的。

**Comment by wangchunming** [comment]
我原先也是用hosts的，但是现在我不得不用shadowsocks了，laod现在的在github的hosts仓库都停了，我这边其实虽然说不能停吧但是我也没什么好办法了。。。

2017年9月20日 09:41，"Lintion" <notifications@github.com>写道：

**Comment by JohnWu17** [comment]
@wangchunming 谢谢您的更新，虽然YOUYUBE不能看，但是GOOGLE还是可以的，希望能继续维护这个项目，感谢。
另外昨天是某个人要爆料，相信很多人都知道了了， 希望19大开完后环境能宽松点，再次感谢。

**Comment by bingleyu** [comment]
google OK,其他的都秒封，qiang 太BT

在 2017年9月20日 下午2:18，JohnWu17 <notifications@github.com>写道：

**Comment by JohnWu17** [comment]
@bingleyu 应该说是YOUTUBE现在看不了，其他都还可以。

**Comment by wangchunming** [comment]
对啊，所以我才挂SS啊，自建的在移动下速度很快，速度有94Mbps（移动4G下测试），移动宽带也有19Mbps（20M宽带）

**Comment by sy618** [comment]
防火墙对一些域名加入特殊封锁名单：
#YouTube
*.googlevideo.com
*.ytimg.com
*.youtube.com
#推特
*.twitter.com

一旦探测到这些域名，立刻就阻断对于IP连接（短暂）。

**Comment by wangchunming** [comment]
@sy618 
对，RST伺候。

**Comment by gnuly** [comment]
twitter 大概是3个月前封的, youtube 的确是昨天, gfw 关键字过滤, connection reset 90 秒
把这两个网站的泛域名指向 127.0.0.1 免得误伤, 如果 google 被 reset 的话就不用写 hosts 了
