### ISSUE TITLE
添加quora【无法处理类问题】

### ISSUE THREAD

**Issue by arthurchan35** [wangchunming/2017hosts#74]
我联通的网，quora通常很卡，能添加一下么。

**Comment by wangchunming** [comment]
对不起，这个问题无法处理，谢谢理解。

**Comment by tianrking** [comment]
把Quora指向这类公共sniproxy服务器任意的一个试下  主站没问题 图片啥的有些麻烦 但是基本功能可以使用 我觉得如果 您方便的话 就加一条吧 Quora的确是个很好的东西。如果不方便的话 LZ可以在使用这个hosts之后 自己加一下就好。
219.76.4.3
219.76.4.4
219.76.4.11
219.76.4.14
219.76.4.69
219.76.4.70
219.76.4.73
219.76.4.74
219.76.4.76
218.254.1.15
