### ISSUE TITLE
随便看了一下你这个IP都不是官方的吧？

### ISSUE THREAD

**Issue by braindevices** [wangchunming/2017hosts#75]
一部分是香港PCCW
```
whois -h whois.radb.net 219.76.4.14
route:              219.76.0.0/19
descr:              PCCW IMS Route Object
origin:             AS4760
notify:             netadmin@imsbiz.com
mnt-by:             MAINT-AS4515
changed:            jacky.sm.lam@pccw.com 20021016
source:             RADB
```
一部分是香港中国电信
```
whois -h whois.radb.net 183.91.33.45
route:          183.91.32.0/20
descr:          CHINANET Hongkong region network
descr:          China Telecom
origin:         AS4134
country:        HK
```
难道是直接用的SNI?
hosts没有round robin, 那么多人盯着用这几个IPs就算墙不封，本身也承受巨大压力，所以经常刷不出来。

**Comment by wangchunming** [comment]
对，ipv4hosts少数地址使用的是官方ip，多数都是SNI，为了保证速度只能这样。

**Comment by braindevices** [comment]
嗯检验了一下
`openssl s_client -CApath /etc/ssl/certs/ -servername www.dropbox.com -tlsextdebug -connect 219.76.4.11:443`
`openssl s_client -CApath /etc/ssl/certs/ -servername www.dropbox.com -tlsextdebug -connect 183.91.33.45:443`
都是返回目标证书
可以安全使用但是估计得想法round robin.
