### ISSUE TITLE
需要添加的网址集中反馈贴

### ISSUE THREAD

**Issue by wangchunming** [wangchunming/2017hosts#76]
各位正在使用本处hosts的亲们你们好：
如果需要添加什么网址，请在本贴中集中反馈，以方便我或者是其他协助维护着集中解决你们的问题，谢谢。

【重要提示】：因为GFW审查变严格了，所以Youtube和Twitter均无法直接通过更改hosts使用，这一点谁都无能为力。
【再次提示】：对某党抱有幻想的可以醒醒了，只要惹急了它们，它们什么事都能干的出来。
【二次提示】：干水军的，网评员的，请自觉绕道，这里不欢迎你们。
【三次提示】：在不久的将来，这里可能会停更，因为越来越多的网站可能无法使用hosts直接连接。

**Comment by Vince-7** [comment]
52.84.246.72 http://d3c33hcgiwev3.cloudfront.net
这个是coursera的链接，麻烦加一下，谢谢

**Comment by MarioX7** [comment]
希望hosts主能够尽力去尝试把youtube和facebook等网站的hosts修好吧。
也同时慰电

**Comment by MSONIT** [comment]
最近IP都不能用了吗？

**Comment by bes1355** [comment]
如果可以的话，希望有一个DMM的hosts。4和6都行。
