### ISSUE TITLE
hosts文件中有很多乱码

### ISSUE THREAD

**Issue by jmdly** [wangchunming/2017hosts#76]
用记事本打开是正常显示的"---"，用其他编辑器打开hosts文件后，gooogle IP部分有很多显示的是乱码。
![123](https://user-images.githubusercontent.com/14197424/27160530-8cccd4f4-51a7-11e7-83f5-06180cae6744.png)

**Comment by BudSun** [comment]
编码格式不对吧

**Comment by wangchunming** [comment]
请你不要改动这个地方，虽然乱码但是可以正常解析。

**Comment by wangchunming** [comment]
下一步我处理一下，感谢反馈。
