### ISSUE TITLE
google服务好像又挂了

### ISSUE THREAD

**Issue by arthurchan35** [wangchunming/2017hosts#78]

**Comment by wh9007** [comment]
是的是的.什么节奏撒!

**Comment by JohnWu17** [comment]
主要是guo爆料太猛，现在堵得很严。

**Comment by 1215909505** [comment]
啥料？

**Comment by Johnandfu** [comment]
还有法律吗

**Comment by DrugsZ** [comment]
现在貌似上不去，是谷歌那里的原因吗

**Comment by wangchunming** [comment]
不行的话我暂时也没办法了，有替代手段的就用替代手段吧。

2017年9月21日 18:58，"DrugsZ" <notifications@github.com>写道：

**Comment by LYT1272478208** [comment]
这里的可以用https://laod.cn/hosts/2017-google-hosts.html

**Comment by spaceliang** [comment]
老D的不能看youtube视频

**Comment by wangchunming** [comment]
我最近一直在想办法恢复，在此期间你们自己有替代手段的就先用着吧。

2017年9月22日 12:40，"spaceliang" <notifications@github.com>写道：

**Comment by arthurchan35** [comment]
@LYT1272478208 
出差在天津，天津联通的网，用不了老D的host。
