### ISSUE TITLE
全部hosts已失效，用的移动宽带

### ISSUE THREAD

**Issue by blacknig** [wangchunming/2017hosts#79]

**Comment by wangchunming** [comment]
是移动出口炸了。。。。

**Comment by blacknig** [comment]
是不是永久用不了了

**Comment by wangchunming** [comment]
@blacknig 你哪里的移动宽带啊，从什么时候开始不能用的。

**Comment by blacknig** [comment]
阳泉的移动宽带，从21号开始不能用的

**Comment by blacknig** [comment]
github上热门的hosts都试过了

**Comment by nxtreaming** [comment]
强烈建议不要使用host方案，因为此方案给自己提供便利的同时，也给那些想封锁 IP的人提供了更大的方便。

-----------------------------------------
Productive. Reliable. Fast.

**Comment by blacknig** [comment]
哦哦 有SS 只是觉得不如host方便

**Comment by crazymrli** [comment]
福建联通的最近也完全用不了了
