### ISSUE TITLE
香港的bing.com的hosts有问题!!!!

### ISSUE THREAD

**Issue by GerGitHub** [wangchunming/2017hosts#79]
无法解析, chrome打开bing.com 您请求的URL有问题...

路由器整了半天, 原来是bing的hosts有问题,删了bing那组hosts就OK了

要改一下了

**Comment by protonhub** [comment]
人家都说了要用https访问难道你不看的吗？
![bing](https://user-images.githubusercontent.com/29473294/27211007-f682b24c-5288-11e7-939d-14324397f102.jpg)
