### ISSUE TITLE
youtube看不了了

### ISSUE THREAD

**Issue by StephenAnboer** [wangchunming/2017hosts#82]
youtube视频看不了了，网站能打开，但是视频不能播放了，校园网ipv6的

**Comment by wangchunming** [comment]
能不能给个聊天工具号码我们私下商量？

**Comment by StephenAnboer** [comment]
？啊？我就是反馈一下情况而已。商量什么呀？

**Comment by wangchunming** [comment]
因为是校园网，我没有条件测试，普通ipv6环境下没有这个问题，所以我需要了解更多情况啊。
如果你不原意的话，那么你就点开youtube详细统计截个图传到图床发上来链接我看看。

**Comment by wangchunming** [comment]
最好能提供你的公网ip（ipv6）方便我排查。

**Comment by StephenAnboer** [comment]
https://github.com/lennylxx/ipv6-hosts/issues/125  这边也在讨论这个问题，我加了你fb
