### ISSUE TITLE
Hosts已改为9.23最新版本，Google等网站仍然无法浏览

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [wangchunming/2017hosts#83]
rt，希望博主能够尽力去修复吧

**Comment by ddok520** [comment]
我们这里已经可以正常使用，湖北电信

**Comment by Lazy-Rabbit-2001** [comment]
@ddok520 我们这边河南电信仍旧无法使用

**Comment by jinyumarine** [comment]
谷歌主页可以打开，但是相册还是不行

**Comment by Lazy-Rabbit-2001** [comment]
@jinyumarine 我这边连谷歌主页都打不开

**Comment by ddok520** [comment]
哎，youtube视频才看10几钟就挂了，现在google有关的服务都打不开了

**Comment by jinyumarine** [comment]
@ddok520 手机上好像正常，相同网络环境，电脑就很多服务不行，但是youtube不管手机还是电脑都不行

**Comment by Lazy-Rabbit-2001** [comment]
@ddok520 希望电脑端能够早点修好吧

**Comment by wangchunming** [comment]
对于这个问题我是没有办法的，墙的问题啊。
Laod的Hosts比我挂的更厉害。。。。

**Comment by crazymrli** [comment]
福建联通，谷歌服务正常，youtube,facebook,T都访问不了，博主这个算是比较稳定的，架不住bigbrother啊

**Comment by RickonChen** [comment]
我这边访问Google是OK的，但是一旦尝试访问YouTube，hosts就会暂时性的失效，过了一会儿又正常了

**Comment by pashawowi** [comment]
上海电信 google youtube都不能访问，最近是挂的厉害

**Comment by jinyumarine** [comment]
Google正常了，就是youtube,facebook还是墙了

**Comment by jinyumarine** [comment]
貌似923谷歌又全部挂了

**Comment by Harley0726** [comment]
又挂了，电脑端赛风不稳定，手机端蓝灯好像不能用。

**Comment by wangchunming** [comment]
对，我已经彻底没有ip能用了。

**Comment by jinyumarine** [comment]
@wangchunming 貌似老D的，刚刚突然可以加载youtube页面，但视频加载不出来，ggoogle主页正常，其他服务还是抽风

**Comment by weridname** [comment]
我使用的天行可以看youtube。但是有流量限制，看不到几个视频就没有了。hosts完全用不了。。扎心了老铁

**Comment by weridname** [comment]
看来不用钱是摆平不了这个事了

**Comment by weridname** [comment]
老D的大概是从上上次修改了之后就一直看不到youtube了

**Comment by Renhj90520** [comment]
不要放弃治疗啊

**Comment by bes1355** [comment]
今天Google也不行了。看来只能用ipv6了。

**Comment by weridname** [comment]
求解如何使用ipv6翻墙

**Comment by bes1355** [comment]
你得有4转6资源。
然后随便找个ipv6的hosts就行了 YouTube一直都是满速。

**Comment by weridname** [comment]
使用原来的hosts也可以吗？

**Comment by bes1355** [comment]
不清楚，自己找ipv6的hosts吧，只要能用基本都是满速。

**Comment by weridname** [comment]
我想下载一个天行vpn。。。发现只能进首页

**Comment by bes1355** [comment]
如果你真的想出墙，就去找下$$吧。

**Comment by weridname** [comment]
昨天一激动，手机给我开了一个vpn

**Comment by weridname** [comment]
所以我现在想说看能不能在电脑端也下载一个来使用
