### ISSUE TITLE
大佬 推特用不了了

### ISSUE THREAD

**Issue by MoeCrazyArea** [wangchunming/2017hosts#84]
好几天了，求修复

**Comment by Ibuki-Suika** [comment]
wangchunming（这个项目的管理员）在首页不是说了么

**Comment by Ibuki-Suika** [comment]
1.因twitter上一些不可描述内容的原因，各地运营商开始干扰https的twitter连接，遇到打不开这个问题你可以使用赛风暂时翻墙上推。

**Comment by Ibuki-Suika** [comment]
他之在前被close的issue里解释过，之前有人问过了。。。
