### ISSUE TITLE
此处host以后都不更新了？

### ISSUE THREAD

**Issue by JameryP** [wangchunming/2017hosts#85]
没有IP用的意思是不是，以后都没有host用了？我在其它地方找了个host，谷歌系大部份可以用，但是youtube不能用，，看来得找VPN了，还得为这么长时间的更新服务感谢您！

**Comment by JohnWu17** [comment]
@JameryP  方便告知下新的HOST么？ 谢谢，

**Comment by JameryP** [comment]
@JohnWu17 不是新的，以前用过的host源，https://laod.cn/hosts/2017-google-hosts.html，这两天我已经在用蓝灯了

**Comment by JohnWu17** [comment]
@JameryP  非常感谢，主要习惯了经常什么不明白的，直接选中右键GOOGLE 搜索，没有HOST GOOGLE用起来也实在是不方便，SS 不能一直挂着。
希望这破会开完会环境会好点吧。
