### ISSUE TITLE
更新了今天host yt瞬间爆炸

### ISSUE THREAD

**Issue by samtone** [wangchunming/2017hosts#86]
wangchunming 看了今天说明youtube秒开体验 马上更新了 谁知道反而不如之前的好了。。 3秒一卡。。144p播放。。。
Connection Speed: 2xxkbps
Buffer Health:0.1-3.xs 之间。。。。。
Network Activity:0-70kb 。。。。。。。

难道我要与yt无缘了吗。。。。。。

**Comment by wangchunming** [comment]
你用的是移动吧？移动暂时没有办法解决
