### ISSUE TITLE
即使不再更新hosts，也请列出你已知的所有涉及被封证书的域名。

### ISSUE THREAD

**Issue by dou4cc** [wangchunming/2017hosts#86]
这个域名清单对某些翻墙软件有很大意义。
@wangchunming 另祝高三加油！

**Comment by sy618** [comment]
#YouTube
> *.googlevideo.com
> *.ytimg.com
> *.youtube.com

#Twitter
> *.twitter.com

#Facebook
> *.facebook.com

这些是我测试出来的。其他的自己去试吧。

**Comment by dou4cc** [comment]
@wangchunming 求被封vimeo证书对应的域名。
