### ISSUE TITLE
最近YTB缓冲速度最高只能到1500kbps左右

### ISSUE THREAD

**Issue by nanjolnoc-cc** [wangchunming/2017hosts#90]
上个月开始用的您的HOSTS一直很不错，YTB速度能上几万（上海电信100M光纤）看4K还是可以得。这几天突然速度就卡在了1500左右，更新了下HOSTS也同样情况。然后试着挂了下VPN（某破解版)但是似乎是被限速了，所有节点都被卡在了5120KBPS的速度。请问有办法解决吗，谢谢。

**Comment by arthurchan35** [comment]
1500kbs。。。这么快，我这自从10几号的hosts开始，看youtube就只能144p的分辨率，240p就得卡

**Comment by wangchunming** [comment]
这属于运营商限制了。
我现在正在马不停蹄的开着电脑扫代理ip呢。。。

**Comment by wangchunming** [comment]
你俩都是电信吗？都是哪个省份的啊？

**Comment by nanjolnoc-cc** [comment]
上海闵行区电信100M光纤 谢谢=))

**Comment by hnxals** [comment]
南京50M联通状况也是最近只能144p

**Comment by Ninzero** [comment]
能否帮我看一下http://store.steampowered.com/能否正常打开，谢谢 @nanjolnoc-cc

**Comment by nanjolnoc-cc** [comment]
我也玩STEAM的 这个月商店界面就一直101错误，其他界面都可以进。但是一直刷新有一定几率可以刷进去商店，多刷新几次，或者直接挂个VPN就好。  这个应该不是hosts的问题，我还原HOSTS也同样，我同学没用过hosts的也有同样情况。应该是电信的问题。 @Ninzero

**Comment by Ninzero** [comment]
我刚刚试了一下，把hosts里的steam部分删了，就正常了，推荐试试 @nanjolnoc-cc

**Comment by arthurchan35** [comment]
我的也是联通。。。现在进youtube自动给我选144p，我真是受不了了。。。240p就开始卡

10几号之前的hosts挺好的，看720p很稳定

**Comment by wangchunming** [comment]
@arthurchan35 其他网站速度怎么样？？？

**Comment by wangchunming** [comment]
我这里移动挺好的，你们能不能也发下你们那里的速度？（图片上传到图床或者是自己的社交平台上）
![](https://ooo.0o0.ooo/2017/06/26/5950e30873d59.png)

**Comment by arthurchan35** [comment]
@wangchunming 
![youtube speed test](https://user-images.githubusercontent.com/6461170/27535966-8a702d7c-5a9f-11e7-939a-60be0627a4e0.png)

10几号的某个hosts之后 google services都有点慢，其他站点都还行。
另外非常感谢添加了quora。

**Comment by nanjolnoc-cc** [comment]
![image](http://a1.qpic.cn/psb?/V13satHM2cA4xU/nfyEhJsa1A8wGfa3Q.bQ.yCZbRnWZW5FXbEKhuI*gqc!/b/dDwBAAAAAAAA&ek=1&kp=1&pt=0&bo=*gKAAgAAAAADJ3w!&tm=1498471200&sce=60-2-2&rf=viewer_4)
上限就到1500左右了 上海电信

**Comment by arthurchan35** [comment]
@nanjolnoc-cc 你这是赤裸裸的炫耀啊

**Comment by samtone** [comment]
广西联通也是悲剧144p。。。。。。估计跟最近要开会了有关系。。。

**Comment by arthurchan35** [comment]
回复里说只能144p包括我在内都是联通。。。。

**Comment by Ibuki-Suika** [comment]
+1
也是联通144p_(:з」∠)_
144p播着都卡（联通100m）

**Comment by arthurchan35** [comment]
公司裏有電信和聯通兩個網絡。用聯通的就只能144p，切換到電信的馬上正常了，720p無壓力。
