### ISSUE TITLE
能否提供resilio sync下载？

### ISSUE THREAD

**Issue by Ninzero** [wangchunming/2017hosts#97]

**Comment by Ninzero** [comment]
我现在根本下载不了最新的文件，可以的话希望提供resilio sync，不用钱也很方便，谢谢

**Comment by Ninzero** [comment]
另外dropbox也相当不稳定，不知道是否有解决方案？谢谢

**Comment by Antecer** [comment]
解决方式是同步本项目到国内的gitoschina ,或者coding也可以.

**Comment by wangchunming** [comment]
好的，马上上架 resilio sync

**Comment by wangchunming** [comment]
还有就是我没有添加这个软件的下载地址到hosts内的原因就是我根本找不到可用ip。
