### ISSUE TITLE
hosts-mobile文件替换不好用呀

### ISSUE THREAD

**Issue by trystudy** [wangchunming/2017hosts#98]
17年7月6日更新的hosts-mobile文件替换手机根目录\ETC的hosts不好使呀。
换其他的hosts文件替换就可以上youtube但是不能播放视频。

这个1.2M大的hosts文件为何不好使呢？两个手机版本的hosts都试过了，手机系统是安卓5.0的。

另外将hosts换成文本格式文件hosts.txt也不好使。
请问这是什么原因？

**Comment by wangchunming** [comment]
稍等，我看看

**Comment by trystudy** [comment]
我是在网页上复制文本后粘贴到记事本上后另存为hosts，再替换到手机里。可是不能用

**Comment by wangchunming** [comment]
大哥诶，你需要用个notepad转换下换行符为unix格式才能放到手机里用的。

**Comment by trystudy** [comment]
感谢：wangchunming  问题解决了。
用Notepad++中Windows与Unix,格式之间的转换格式详见链接教程
希望大家不要再像我一样犯错
[https://www.crifan.com/files/doc/docbook/rec_soft_npp/release/htmls/npp_func_windows_unix_mac.html](url)
