### ISSUE TITLE
hosts-mobile文件替换不好用呀

### ISSUE THREAD

**Issue by trystudy** [wangchunming/2017hosts#99]
17年7月6日更新的hosts-mobile文件替换手机根目录\ETC的hosts不好使呀。
换其他的hosts文件替换就可以上youtube但是不能播放视频。

这个1.2M大的hosts文件为何不好使呢？两个手机版本的hosts都试过了，手机系统是安卓5.0的。
而电脑版的在电脑上好用。

另外将hosts换成文本格式文件hosts.txt也不好使。
请问这是什么原因？

**Comment by wangchunming** [comment]
换行符的事，我重新发一遍
